# configuration for "master" branch
- branches:
    only:
      - master

  version: 1.1.{build}
  image: Visual Studio 2017

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

  configuration:
    - Release

  environment:
    TreatWarningsAsErrors: false

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - dotnet restore SS.Restriction.sln

  build:
    project: SS.Restriction.sln # path to Visual Studio solution or project
    publish_nuget: true

  deploy:
    provider: NuGet
    server: # remove to push to NuGet.org
    api_key:
      secure: B9umZPwBVx2TMfYt7G1Eppy7XX0FkqWioXxwR+lKv5XVRc6ezjOXP8D9iuisOWBF
    skip_symbols: false
    symbol_server: # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/

# configuration for "dev" branch
- branches:
    only:
      - dev

  version: 1.1.{build}-beta
  image: Visual Studio 2017

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

  configuration:
    - Release

  environment:
    TreatWarningsAsErrors: false

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - dotnet restore SS.Restriction.sln

  build:
    project: SS.Restriction.sln # path to Visual Studio solution or project
    publish_nuget: true

  deploy:
    provider: NuGet
    server: # remove to push to NuGet.org
    api_key:
      secure: B9umZPwBVx2TMfYt7G1Eppy7XX0FkqWioXxwR+lKv5XVRc6ezjOXP8D9iuisOWBF
    skip_symbols: false
    symbol_server: # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/
